<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package StudioPress\Genesis
 * @author  StudioPress
 * @license GPL-2.0-or-later
 * @link    https://my.studiopress.com/themes/genesis/
 */

$genesis_tax = get_taxonomy( $object->taxonomy );
?>
<h2><?php echo esc_html( $genesis_tax->labels->singular_name ) . ' ' . esc_html__( 'Archive Settings', 'genesis' ); ?></h2>
<table class="form-table">
	<tbody>
		<tr class="form-field">
			<th scope="row"><label for="genesis-meta[headline]"><?php esc_html_e( 'Archive Headline', 'genesis' ); ?></label></th>
			<td>
				<input name="genesis-meta[headline]" id="genesis-meta[headline]" type="text" value="<?php echo esc_attr( get_term_meta( $object->term_id, 'headline', true ) ); ?>" size="40" />
				<p class="description">
					<?php
					if ( genesis_a11y( 'headings' ) ) {
						esc_html_e( 'Your child theme uses accessible headings. If you leave this blank, the default accessible heading will be used.', 'genesis' );
					} else {
						esc_html_e( 'Leave empty if you do not want to display a headline.', 'genesis' );
					}
					?>
				</p>
			</td>
		</tr>
		<tr class="form-field">
			<th scope="row"><label for="genesis-meta-intro-text"><?php esc_html_e( 'Archive Intro Text', 'genesis' ); ?></label></th>
			<td>
				<?php
				wp_editor(
					get_term_meta( $object->term_id, 'intro_text', true ),
					'genesis-meta-intro-text',
					array(
						'textarea_name' => 'genesis-meta[intro_text]',
					)
				);
				?>
				<p class="description"><?php esc_html_e( 'Leave empty if you do not want to display any intro text.', 'genesis' ); ?></p>
			</td>
		</tr>
        <tr class="form-field">
            <th scope="row"><label for="genesis-meta[headline_image]"><?php esc_html_e( 'Archive Headline Image', 'genesis' ); ?></label></th>
            <td>
                <?php
                $image_id = get_term_meta( $object->term_id, 'headline_image_id', true );
                ?>
                <input type="hidden" name="genesis-meta[headline_image]" id="genesis-meta[headline_image]" value="<?php echo esc_attr( get_term_meta( $object->term_id, 'headline_image', true ) ); ?>" />
                <input type="hidden" name="genesis-meta[headline_image_id]" id="genesis-meta[headline_image_id]" value="<?php echo esc_attr( $image_id ); ?>" />
                <button class="button setting-upload"><?php _e('Select/Upload', WPS_PARTNERS_DOMAIN ) ?></button>
                <div class="preview">
		            <?php
		            if ( $image_id ) {
			            echo wp_get_attachment_image( $image_id );
		            } else {
			            echo '<img style="display:none;" class="attachment-thumbnail size-thumbnail" alt="" width="150" height="150">';
		            }
		            ?>
                </div>
                <p class="description">
		            <?php
		            esc_html_e( 'Optional. Upload an image', WPS_PARTNERS_DOMAIN );
		            ?>
                </p>
            </td>
        </tr>
	</tbody>
</table>

<script>
    (function($) {
        $(document).ready(function($){

            var customUploader,
                $clickElem = $(".setting-upload"),
                $targetImage = $('.wrap input[name="genesis-meta[headline_image]"]'),
                $previewDiv = $(".preview"),
                $targetImageID = $('.wrap input[name="genesis-meta[headline_image_id]"]');

            $clickElem.click(function(e) {
                e.preventDefault();
                //If the uploader object has already been created, reopen the dialog
                if (customUploader) {
                    customUploader.open();
                    return;
                }
                //Extend the wp.media object
                customUploader = wp.media.frames.file_frame = wp.media({
                    title: "<?php _e( 'Choose Image', WPS_PARTNERS_DOMAIN ); ?>",
                    button: {
                        text: "<?php _e( 'Choose Image', WPS_PARTNERS_DOMAIN ); ?>"
                    },
                    multiple: false
                });
                //When a file is selected, grab the URL and set it as the text field's value
                customUploader.on('select', function() {
                    debugger;
                    var attachment = customUploader.state().get('selection').first().toJSON();

                    $targetImage.val(attachment.url);
                    $targetImageID.val(attachment.id);

                    $previewDiv.find("img").remove();
                    $previewDiv.html('<img src="'+attachment.sizes.thumbnail.url+'" height="' + attachment.sizes.thumbnail.height + '" width="' + attachment.sizes.thumbnail.width + '">')

                });
                //Open the uploader dialog
                customUploader.open();
            });
        });
    })(jQuery);
</script>
